name: Continuous Integration

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: jsumners-nr/gha-node-deps-divergent@643628fe0da51ec025e984c4644f17fd9f9e93f6
        id: deps
        with:
          base-sha: ${{ github.base_ref }}
          current-sha: ${{ github.sha }}
          package-name: 'nothing'
      - env:
          DIVERGENT: ${{ steps.deps.outputs.divergent }}
        run: |
          echo "divergent: ${DIVERGENT}"
