name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  should-run:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      has_changes: ${{ steps.filter.outputs.javascript }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            javascript:
              - '**/*.js'
              - '**/*.json'

  lint:
    needs: should-run
    if: needs.should-run.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run lint

  test:
    needs: should-run
    if: needs.should-run.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run test

  all-clear:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: All checks passed
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some checks failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
